version: '3.9'

services:
  blogserver:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blogserver
    hostname: blogserver
    privileged: true
    volumes:
      - ./scripts:/scripts                           # Platform scripts
      - users_data:/home                             # Home for authors/users
      - /etc/passwd:/etc/passwd:ro                   # Sync user info
      - /etc/shadow:/etc/shadow:ro
      - /etc/group:/etc/group:ro
    networks:
      - internal
    depends_on:
      - db
    mem_limit: 512m
    cpus: 0.5
    pids_limit: 100

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: blogdb
    hostname: blogdb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: blogdb
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro  # DB schema and setup
    networks:
      - internal
    mem_limit: 256m
    cpus: 0.4
    pids_limit: 100

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    hostname: blog.in
    depends_on:
      - blogserver
    ports:
      - "80:80"                # HTTP access
      - "443:443"              # HTTPS access
    volumes:
      - users_data:/home:ro                      # Access to blogs in /home/authors/<author>/public
      - ./nginx/certs:/etc/nginx/certs:ro        # SSL certificates
    networks:
      - internal
      - external
    mem_limit: 128m
    cpus: 0.2
    pids_limit: 50

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"              # http://localhost:8080 for DB access
    environment:
      PMA_HOST: blogdb
      MYSQL_ROOT_PASSWORD: root123
    networks:
      - internal
    mem_limit: 128m
    cpus: 0.2
    pids_limit: 50

volumes:
  users_data:        # Shared /home directory
  db_data:           # DB persistence

networks:
  internal:
    driver: bridge
  external:
    driver: bridge
