services:
  db:
    image: mysql:5.7
    restart: always
    env_file: .env
    volumes:
      - ./chat.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

  chat-server:
    build: .
    depends_on:
      - db
    ports:
      - "8888:8888"
    env_file:
      - .env
