#!/bin/bash

USERS_FILE="/scripts/users.yaml"

remove_users() {
  section=$1
  homedir="/home/$section"

  i=0
  while true; do
    entry=$(yq ".$section[$i]" "$USERS_FILE")
    [ "$entry" == "null" ] && break

    username=$(echo "$entry" | yq ".username")
    userdel -r "$username" 2>/dev/null
    echo "Removed user: $username"

    i=$((i+1))
  done

  rm -rf "$homedir"
  echo "Deleted home directory for $section"
}

# Remove all user types
remove_users users
remove_users authors
remove_users mods
remove_users admins

# Remove user groups
groupdel g_user 2>/dev/null
groupdel g_author 2>/dev/null
groupdel g_mod 2>/dev/null
groupdel g_admin 2>/dev/null
echo "Removed all groups"

# Optional: Remove ACLs set by initUsers
setfacl -bR /home 2>/dev/null
echo "Cleaned up ACLs"