#!/bin/bash

username="$1"

if [[ -z "$username" ]]; then
    echo "Usage: depromote <username>"
    exit 1
fi

author_dir="/home/authors/$username"
user_dir="/home/users/$username"

if [[ ! -d "$author_dir" ]]; then
    echo "Author directory not found"
    exit 1
fi

# Remove symlinks from all users' all_blogs
for path in /home/users/*/all_blogs; do
    rm -f "$path/$username"
done

usermod -g "$username" -G g_user -d "$user_dir" "$username"
mv "$author_dir" "$user_dir"

chown -R "$username:$username" "$user_dir"
echo "User '$username' has been demoted to regular user."
