#!/bin/bash

username="$SUDO_USER"
REQUESTS_FILE="/scripts/requests.yaml"

if [[ -z "$username" ]]; then
    echo "Please run with sudo"
    exit 1
fi

req_exists=$(yq e ".requests | index(\"$username\")" "$REQUESTS_FILE")

if [[ "$req_exists" == "null" ]]; then
    yq -i ".requests += [\"$username\"]" "$REQUESTS_FILE"
    echo "Request submitted. Waiting for admin approval."
else
    echo "Request already submitted. Please wait for admin approval."
fi
