#!/bin/bash

CRON_LINE='14 15 * 2,5,8,11 * /scripts/adminpannel'

( crontab -l 2>/dev/null | grep -F "$CRON_LINE" ) && {
  exit 0
}
( crontab -l 2>/dev/null; echo "$CRON_LINE" ) | crontab -
echo "Cron job added:"
echo "$CRON_LINE"
