#!/bin/bash

SUBSCRIPTIONS_FILE="/scripts/subscriptions.yaml"
author="$1"

if [[ -z "$author" ]]; then
    echo "Usage: subscribe <authorname>"
    exit 1
fi

if [[ ! -d "/home/authors/$author" ]]; then
    echo "Author '$author' does not exist."
    exit 1
fi

username="$(whoami)"
target="/home/users/$username/subscribed_blogs/$author"

mkdir -p "/home/users/$username/subscribed_blogs"

if [[ -L "$target" ]]; then
    yq -i "del(.[\"$author\"][] | select(. == \"$username\"))" "$SUBSCRIPTIONS_FILE"
    rm "$target"
    echo "Unsubscribed from '$author'"
else
    yq -i ".[\"$author\"] += [\"$username\"]" "$SUBSCRIPTIONS_FILE"
    ln -sfn "/home/authors/$author/subscribers_only" "$target"
    echo "Subscribed to '$author'"
fi
